# Generated by Django 4.2.7 on 2024-07-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_message_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('class_type', models.CharField(choices=[('Physical', 'Physical'), ('Online via Zoom', 'Online via Zoom')], max_length=50)),
                ('class_time_slots', models.CharField(choices=[('Weekly', 'Weekly'), ('Weekend', 'Weekend')], max_length=50)),
                ('preferred_start_date', models.DateField()),
                ('employer_name', models.CharField(max_length=100)),
                ('position_at_work', models.CharField(max_length=100)),
                ('owns_laptop', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('address', models.CharField(max_length=100)),
                ('course_module', models.CharField(choices=[('ICDL', 'ICDL'), ('Web design (HTML, CSS, JS)', 'Web design (HTML, CSS, JS)'), ('Web development with Python Django', 'Web development with Python Django')], max_length=50)),
                ('referral_source', models.CharField(choices=[('A Friend', 'A Friend'), ('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('WhatsApp', 'WhatsApp'), ('Google Search', 'Google Search'), ('Youtube', 'Youtube'), ('TikTok', 'TikTok'), ('From School', 'From School'), ('National Science Week 2023', 'National Science Week 2023'), ('Other', 'Other')], max_length=50)),
                ('referral_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('agree_to_terms', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('school', models.CharField(max_length=100)),
                ('residence', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('student_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('code_camp', models.CharField(choices=[('Form 6 Vacationers Code Camp (Mar - July)', 'Form 6 Vacationers Code Camp (Mar - July)'), ('51st Code Camp (MAY)', '51st Code Camp (MAY)'), ('Private Class', 'Private Class'), ('Easter Break Code Camp', 'Easter Break Code Camp'), ('Artificial Intelligence (Saturdays)', 'Artificial Intelligence (Saturdays)'), ('Summer Code Camp', 'Summer Code Camp')], max_length=50)),
                ('mode_of_school', models.CharField(choices=[('Day', 'Day'), ('Boarding', 'Boarding')], max_length=50)),
                ('type_of_school', models.CharField(choices=[('National', 'National'), ('International', 'International'), ('Semi-International', 'Semi-International')], max_length=50)),
                ('course_module', models.CharField(choices=[('Scratch Beginners', 'Scratch Beginners'), ("2D Game Dev't with Scratch", "2D Game Dev't with Scratch"), ('Python Beginners', 'Python Beginners')], max_length=50)),
                ('preferred_class_type', models.CharField(choices=[("Private Physical at the Client's home", "Private Physical at the Client's home"), ('Private Physical at Academy Offices', 'Private Physical at Academy Offices'), ('Private Online (Via Zoom)', 'Private Online (Via Zoom)'), ('General Physical (ICT House)', 'General Physical (ICT House)'), ('General online (via Zoom)', 'General online (via Zoom)')], max_length=50)),
                ('next_term_start', models.DateField()),
                ('parent_full_name', models.CharField(max_length=100)),
                ('parent_title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Miss.', 'Miss.')], max_length=10)),
                ('parent_phone', models.CharField(max_length=15)),
                ('parent_occupation', models.CharField(max_length=100)),
                ('referral_source', models.CharField(choices=[('A Friend', 'A Friend'), ('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('WhatsApp', 'WhatsApp'), ('Google Search', 'Google Search'), ('Youtube', 'Youtube'), ('TikTok', 'TikTok'), ('From School', 'From School'), ('National Science Week 2023', 'National Science Week 2023'), ('Other', 'Other')], max_length=50)),
                ('referral_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('agree_to_terms', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
